import React, { useState } from 'react';
import { ShieldCheck, Hash, CheckCircle2, Lock, Copy, Check } from 'lucide-react';
import { Badge } from '../common/Badge';

interface HashProvenanceProps {
  sha256: string;
  sourceDoc: string;
}

export const HashProvenance: React.FC<HashProvenanceProps> = ({ sha256, sourceDoc }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(sha256);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-950/90 p-4 font-mono text-xs space-y-2.5">
      <div className="flex items-center justify-between border-b border-slate-800 pb-2">
        <div className="flex items-center gap-1.5 text-emerald-400 font-bold uppercase">
          <ShieldCheck className="h-4 w-4" />
          <span>Cryptographic Provenance Seal</span>
        </div>
        <Badge variant="success" size="xs">
          SHA-256 VERIFIED
        </Badge>
      </div>

      <div className="text-[11px] text-slate-400">
        Every recommendation generated by KAVACHA is cryptographically sealed against its air-gapped SOP source chunk to prevent unauthorized alterations or data tampering.
      </div>

      <div className="flex items-center justify-between bg-slate-900 px-3 py-2 rounded-lg border border-slate-800 text-[10px]">
        <div className="truncate mr-2">
          <span className="text-slate-500">DIGEST:</span>{' '}
          <span className="text-cyan-300">{sha256}</span>
        </div>
        <button
          onClick={handleCopy}
          className="text-slate-400 hover:text-cyan-400 transition shrink-0"
          title="Copy Hash"
        >
          {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5" />}
        </button>
      </div>

      <div className="grid grid-cols-2 gap-2 text-[10px] text-slate-500">
        <div>Asset: <span className="text-slate-300">{sourceDoc}</span></div>
        <div>Integrity: <span className="text-emerald-400">100% UNMODIFIED</span></div>
      </div>
    </div>
  );
};