import { Message, PromptPreset } from '../types/chat';
import { IngestedDocument, VectorChunk } from '../types/document';
import { EquipmentImageSample } from '../types/vision';
import { IndustrialAgent, AgentTask, AgentLogEntry } from '../types/agent';
import { MachineContext, AirGapTelemetry, ConfidenceMetrics, SecurityCertification } from '../types/security';

export const MOCK_MACHINES: MachineContext[] = [
  {
    id: 'GT-01',
    tag: 'TAG-GT01-TURB-01',
    name: 'Frame 9F Heavy Duty Gas Turbine',
    plantArea: 'Power Block 1 - Turbine Hall',
    type: 'Heavy Turbomachinery',
    status: 'warning',
    currentRpm: 3605,
    temperatureC: 542.8,
    pressureBar: 18.4,
    vibrationMmS: 7.42,
    lastInspection: '2026-08-28T08:30:00Z',
    silRating: 'SIL-3',
  },
  {
    id: 'P-402',
    tag: 'TAG-P402-BFP-02',
    name: 'High-Pressure Boiler Feed Pump #2',
    plantArea: 'Boiler Island - Bay 3',
    type: 'Centrifugal Multi-Stage',
    status: 'nominal',
    currentRpm: 2980,
    temperatureC: 88.3,
    pressureBar: 164.2,
    vibrationMmS: 2.15,
    lastInspection: '2026-09-02T14:15:00Z',
    silRating: 'SIL-2',
  },
  {
    id: 'TR-801',
    tag: 'TAG-TR801-XFMR-01',
    name: 'Generator Step-Up Transformer 400kV',
    plantArea: 'Switchyard Yard A',
    type: 'Oil-Immersed Autotransformer',
    status: 'warning',
    currentRpm: 0,
    temperatureC: 94.6,
    pressureBar: 1.2,
    vibrationMmS: 0.85,
    lastInspection: '2026-09-04T11:00:00Z',
    silRating: 'SIL-3',
  },
  {
    id: 'HX-105',
    tag: 'TAG-HX105-COND-01',
    name: 'Main Surface Condenser & Heat Exchanger',
    plantArea: 'Cooling Bay East',
    type: 'Shell & Tube Exchanger',
    status: 'nominal',
    currentRpm: 0,
    temperatureC: 44.2,
    pressureBar: 0.08,
    vibrationMmS: 0.32,
    lastInspection: '2026-08-15T09:00:00Z',
    silRating: 'SIL-2',
  },
];

export const MOCK_PROMPT_PRESETS: PromptPreset[] = [
  {
    id: 'preset-1',
    title: 'Analyze Turbine Vibration Surge',
    description: 'Diagnose 7.42 mm/s vibration surge at Bearing #4 on GT-01 against ISO-10816-3 Zone C/D limits.',
    category: 'vibration',
    machineId: 'GT-01',
    prompt: 'Gas Turbine GT-01 Bearing #4 has spiked to 7.42 mm/s RMS at 3600 RPM. Query SCADA vibration spectrum, compare against ISO-10816-3 Zone limits, inspect recent oil debris analysis, and outline the immediate step-by-step mitigation SOP.',
    badge: 'High Priority',
  },
  {
    id: 'preset-2',
    title: 'Transformer Bushing Thermal Hotspot',
    description: 'Evaluate FLIR thermography anomaly (+41.8°C delta) on TR-801 400kV Phase B bushing.',
    category: 'thermal',
    machineId: 'TR-801',
    prompt: 'Evaluate the infrared thermography report for Transformer TR-801 Phase B high-voltage bushing showing +41.8°C delta over ambient. Is dielectric breakdown imminent? Cross-reference IEEE C57.104 and recommend load de-rating.',
    badge: 'Thermal Risk',
  },
  {
    id: 'preset-3',
    title: 'Boiler Feed Pump LOTO Protocol',
    description: 'Generate SIL-3 compliant Lockout/Tagout isolation steps for P-402 seal replacement.',
    category: 'sop',
    machineId: 'P-402',
    prompt: 'Prepare an air-gapped Lockout/Tagout (LOTO) isolation procedure for Boiler Feed Pump P-402 mechanical seal overhaul. Identify physical isolation valves, electrical breakers, suction/discharge blind flanges, and zero-energy verification steps.',
    badge: 'Safety LOTO',
  },
  {
    id: 'preset-4',
    title: 'Verify IEC 62443 Air-Gap Status',
    description: 'Audit network boundary enforcement and confirm zero exfiltration vectors.',
    category: 'compliance',
    machineId: 'GT-01',
    prompt: 'Perform an immediate air-gap security audit. Verify physical network disconnection, examine local inference vLLM weights hash, and confirm zero egress traffic across all OT subnet gateways.',
    badge: 'Security Audit',
  },
];

export const MOCK_INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-sys-1',
    role: 'system',
    content: 'KAVACHA Industrial AI Copilot initialized in STRICT AIR-GAP MODE. Local model: Mistral-7B-Industrial-v2 (vLLM on Dual RTX A6000 Ada). Network isolation verified: 0 outbound packets.',
    timestamp: '2026-09-06T05:30:00Z',
  },
  {
    id: 'msg-user-1',
    role: 'user',
    content: 'Gas Turbine GT-01 Bearing #4 has spiked to 7.42 mm/s RMS at 3600 RPM. Query SCADA vibration spectrum, compare against ISO-10816-3 Zone limits, inspect recent oil debris analysis, and outline the immediate step-by-step mitigation SOP.',
    timestamp: '2026-09-06T05:31:10Z',
    machineId: 'GT-01',
  },
  {
    id: 'msg-ai-1',
    role: 'assistant',
    content: `### 🚨 Urgent Diagnostic Finding: GT-01 Bearing #4 Vibration Exceedance

Based on real-time SCADA telemetry and cross-referenced plant SOPs, **GT-01 Bearing #4 vibration at 7.42 mm/s RMS is in critical ISO 10816-3 Zone D ("Unrestricted operation may cause catastrophic structural damage")**.

---

#### 1. Telemetry & FFT Spectrum Analysis
- **Overall Vibration Level**: **7.42 mm/s RMS** (Threshold Zone C: 4.5 mm/s, Zone D Trip: 7.10 mm/s)
- **Dominant Frequency Peak**: **1X Shaft Speed (60.1 Hz)** accounting for 68% of spectral energy, with synchronous phase shift of +44°.
- **Sub-harmonic Peak**: Moderate 0.43X oil whirl sub-synchronous component detected at 25.8 Hz.
- **Lube Oil Telemetry**: Bearing #4 return temperature is **89.4°C** (+14.2°C elevated over 30-day moving average).

---

#### 2. Immediate Recommended SOP Actions (SOP-MNT-GT01-BRG4)
1. **Reduce MW Load Immediately**: Throttle output from 280 MW to base idle (120 MW) at a controlled ramp rate of ≤ 10 MW/min to avoid thermal shock.
2. **Engage Auxiliary Lube Oil Pump (P-101B)**: Ensure pressure remains at **2.85 bar** to prevent boundary lubrication failure.
3. **Trigger Borescope & Visual Inspection**: Inspect Stage 4 compressor blades and journal pads for mechanical rubbing and fatigue spalling.
4. **Prepare Safety Interlock Trip**: If vibration persists > 7.50 mm/s for > 45 seconds, allow automatic SIL-3 protective shutdown.`,
    timestamp: '2026-09-06T05:31:18Z',
    machineId: 'GT-01',
    confidenceScore: 95.4,
    safetyAlertLevel: 'critical',
    reasoningSteps: [
      {
        id: 'r-1',
        title: 'Query SCADA Modbus Telemetry Bus',
        description: 'Retrieved 120s buffer for TAG-GT01-VIB-BRG4, lube oil temperature sensors, and rotational tachometer.',
        status: 'completed',
        durationMs: 38,
        timestamp: '05:31:11',
      },
      {
        id: 'r-2',
        title: 'Run Fast Fourier Transform (FFT) Spectral Decomposition',
        description: 'Calculated 1X, 2X, and sub-synchronous vibration harmonics. Detected dominant unbalance & oil whirl signature.',
        status: 'completed',
        durationMs: 64,
        timestamp: '05:31:13',
      },
      {
        id: 'r-3',
        title: 'Local Vector Store SOP Similarity Retrieval',
        description: 'Searched 4,280 local document chunks using bge-large on-prem. Top hit: SOP-MNT-GT01-BRG4 (Cosine Similarity: 0.962).',
        status: 'completed',
        durationMs: 82,
        timestamp: '05:31:15',
      },
      {
        id: 'r-4',
        title: 'Safety Interlock (SIL-3) Rule Evaluation',
        description: 'Verified trip threshold envelope: current 7.42 mm/s exceeds automatic warning limit; manual derating protocol active.',
        status: 'completed',
        durationMs: 22,
        timestamp: '05:31:17',
      },
    ],
    toolCalls: [
      {
        id: 'tool-1',
        toolName: 'scada_telemetry_query',
        displayName: 'SCADA Telemetry Bus Query',
        status: 'success',
        executionTimeMs: 42,
        input: { tag: 'TAG-GT01-VIB-BRG4', windowSec: 120 },
        output: { rmsMmS: 7.42, peakMmS: 11.2, rpm: 3605, tempC: 89.4, lubeOilPressBar: 2.84 },
      },
      {
        id: 'tool-2',
        toolName: 'vibration_fft_spectrum',
        displayName: 'FFT Spectral Decomposition Engine',
        status: 'success',
        executionTimeMs: 78,
        input: { sampleRateHz: 10240, window: 'Hanning', bins: 2048 },
        output: { peak1xFreqHz: 60.1, peak1xAmp: 5.08, subHarmonicHz: 25.8, subHarmonicAmp: 1.84, status: 'ZONE_D_SURGE' },
      },
      {
        id: 'tool-3',
        toolName: 'sop_vector_search',
        displayName: 'Air-Gapped SOP Vector Search',
        status: 'success',
        executionTimeMs: 91,
        input: { query: 'GT-01 Bearing 4 high vibration ISO 10816 Zone D emergency mitigation', k: 3 },
        output: { matchedDocs: ['SOP-MNT-GT01-BRG4', 'ISO-10816-3', 'P&ID-SYS-TURB-01'], topScore: 0.962 },
      },
    ],
    citations: [
      {
        id: 'cit-1',
        documentId: 'doc-sop-gt01-brg4',
        documentName: 'SOP-MNT-GT01-BRG4: Vibration Exceedance Protocol',
        page: 4,
        section: 'Section 3.2: Immediate Ramp-down Schedule',
        snippet: 'When Bearing #4 vibration exceeds 7.10 mm/s RMS, the shift engineer must immediately commence controlled load shedding to ≤ 120 MW at a ramp rate not exceeding 10 MW/min.',
        relevanceScore: 96.2,
        pAndIdTag: 'TAG-GT01-VIB-BRG4',
        sha256: '9f83c11e77864e2e28a5cf538b812efd91bc5a2c4e610d061c02ab9b4183d254',
      },
      {
        id: 'cit-2',
        documentId: 'doc-iso-10816',
        documentName: 'ISO-10816-3: Mechanical Vibration Evaluation',
        page: 12,
        section: 'Table A.1: Rigid Foundation Class I Turbines',
        snippet: 'Zone A (0-2.3 mm/s): New machine. Zone B (2.3-4.5 mm/s): Unrestricted. Zone C (4.5-7.1 mm/s): Limited duration. Zone D (>7.1 mm/s): Damage imminent; trip mandatory.',
        relevanceScore: 94.8,
        pAndIdTag: 'ISO-STD-10816',
        sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      },
    ],
  },
];

export const MOCK_DOCUMENTS: IngestedDocument[] = [
  {
    id: 'doc-sop-gt01-brg4',
    name: 'SOP-MNT-GT01-BRG4_Vibration_Exceedance.pdf',
    category: 'SOP',
    fileType: 'pdf',
    sizeBytes: 3840200,
    uploadDate: '2026-08-20T10:15:00Z',
    status: 'indexed',
    chunksCount: 142,
    classification: 'Air-Gap Golden',
    sha256Hash: '9f83c11e77864e2e28a5cf538b812efd91bc5a2c4e610d061c02ab9b4183d254',
    plantUnit: 'Gas Turbine GT-01',
    author: 'Chief Reliability Eng. S. Mehta',
    version: 'Rev 4.2',
    summary: 'Standard emergency shutdown and derating procedures for Bearing #4 journal and thrust pads during dynamic unbalance.',
  },
  {
    id: 'doc-iso-10816',
    name: 'ISO-10816-3_Industrial_Vibration_Norms.pdf',
    category: 'Manual',
    fileType: 'pdf',
    sizeBytes: 8412000,
    uploadDate: '2026-08-18T14:22:00Z',
    status: 'indexed',
    chunksCount: 388,
    classification: 'Restricted',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    plantUnit: 'Plant-Wide Standard',
    author: 'International Standards Organization',
    version: '2022 Edition',
    summary: 'Harmonized vibration criteria for industrial machines on rigid foundations above 300 kW.',
  },
  {
    id: 'doc-pid-p402',
    name: 'P&ID-SYS-FEED-402_Boiler_Feed_Hydraulics.dwg',
    category: 'P&ID',
    fileType: 'dwg',
    sizeBytes: 15420100,
    uploadDate: '2026-08-22T11:45:00Z',
    status: 'indexed',
    chunksCount: 215,
    classification: 'Air-Gap Golden',
    sha256Hash: 'b4c73f912e84d72b5394821a04918e38d4920b12a849b2938475812903847581',
    plantUnit: 'Feedwater Island P-402',
    author: 'Instrumentation Lead R. Deshmukh',
    version: 'Rev C-Final',
    summary: 'Piping and instrumentation diagram showing seal flush plan 53A barrier fluid loop and suction/discharge interlocks.',
  },
  {
    id: 'doc-osha-loto',
    name: 'SOP-SAF-LOTO-1910_Energy_Isolation.pdf',
    category: 'SOP',
    fileType: 'pdf',
    sizeBytes: 2450000,
    uploadDate: '2026-08-25T09:10:00Z',
    status: 'indexed',
    chunksCount: 88,
    classification: 'Confidential',
    sha256Hash: 'c839201f84712938471928471928374910293847192837491827394857192837',
    plantUnit: 'Plant-Wide Safety',
    author: 'EHS Directorate',
    version: '2026.1',
    summary: 'Mandatory zero-energy state verification, lockbox protocols, and tagout sequence for all high-pressure machinery.',
  },
  {
    id: 'doc-xfmr-dga',
    name: 'MANUAL-TR801_Transformer_DGA_Analysis.pdf',
    category: 'Manual',
    fileType: 'pdf',
    sizeBytes: 6120000,
    uploadDate: '2026-08-30T16:00:00Z',
    status: 'indexed',
    chunksCount: 194,
    classification: 'Restricted',
    sha256Hash: 'd748291038475819283746591029384756102938475610293847561029384756',
    plantUnit: 'Switchyard TR-801',
    author: 'Substation Electrical Group',
    version: 'Rev 2.0',
    summary: 'Duval triangle and IEEE gas ratio interpretation for thermal winding faults in large power autotransformers.',
  },
];

export const MOCK_CHUNKS: VectorChunk[] = [
  {
    id: 'chunk-101',
    documentId: 'doc-sop-gt01-brg4',
    docName: 'SOP-MNT-GT01-BRG4_Vibration_Exceedance.pdf',
    chunkIndex: 12,
    pageNumber: 4,
    content: 'SECTION 3.2 - HIGH VIBRATION MITIGATION PROTOCOL: In the event that Bearing #4 radial vibration velocity exceeds 7.10 mm/s RMS (ISO Zone D threshold), the distributed control system (DCS) operator must initiate rapid controlled load shedding to base idle (120 MW). Monitor temperature of lube oil return line (TE-404B) continuously. If vibration exceeds 7.80 mm/s RMS or oil return temperature exceeds 95.0°C, the operator must execute emergency trip sequence TRIP-SEQ-01 immediately.',
    relevanceScore: 96.2,
    tags: ['Vibration', 'Bearing #4', 'Zone D', 'Emergency Trip', 'Lube Oil'],
    pAndIdRef: 'TAG-GT01-VIB-BRG4',
    sha256: '9f83c11e77864e2e28a5cf538b812efd91bc5a2c4e610d061c02ab9b4183d254',
  },
  {
    id: 'chunk-102',
    documentId: 'doc-iso-10816',
    docName: 'ISO-10816-3_Industrial_Vibration_Norms.pdf',
    chunkIndex: 28,
    pageNumber: 12,
    content: 'TABLE A.1 - VIBRATION SEVERITY CRITERIA: For Group 1 large rotating machines (nominal power > 300 kW, shaft height > 315 mm on rigid foundation): Zone A (0 to 2.3 mm/s RMS) represents newly commissioned machinery. Zone B (2.3 to 4.5 mm/s RMS) represents acceptable long-term unrestricted operation. Zone C (4.5 to 7.1 mm/s RMS) represents unsatisfactory operation; remedial measures required during next planned shutdown. Zone D (> 7.1 mm/s RMS) indicates vibration severity sufficient to cause rapid mechanical damage; immediate corrective action or shutdown mandatory.',
    relevanceScore: 94.8,
    tags: ['ISO 10816-3', 'Severity Zones', 'Vibration Limits', 'Turbomachinery'],
    pAndIdRef: 'ISO-STD-10816',
    sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'chunk-103',
    documentId: 'doc-pid-p402',
    docName: 'P&ID-SYS-FEED-402_Boiler_Feed_Hydraulics.dwg',
    chunkIndex: 5,
    pageNumber: 1,
    content: 'P&ID DRAWING NOTE 4: Mechanical seal flush plan API 53A utilizes a pressurized barrier fluid reservoir (RES-402). Barrier pressure must maintain a minimum differential of +1.5 bar above the internal stuffing box pressure (PT-402S). Low barrier pressure alarm (PAL-402) triggers at < 12.5 bar and enforces automatic lockout on motor contactor MC-402.',
    relevanceScore: 89.4,
    tags: ['API 53A', 'Mechanical Seal', 'P-402', 'Interlock', 'Barrier Fluid'],
    pAndIdRef: 'TAG-P402-SEAL-53A',
    sha256: 'b4c73f912e84d72b5394821a04918e38d4920b12a849b2938475812903847581',
  },
];

export const MOCK_VISION_SAMPLES: EquipmentImageSample[] = [
  {
    id: 'sample-vision-1',
    title: 'GT-01 Stage 4 Compressor Blade Fatigue Crack',
    machineId: 'GT-01',
    component: 'Stage 4 Rotor Blade Leading Edge',
    timestamp: '2026-09-06T04:12:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=1200&q=80',
    imageType: 'visible',
    ambientTempC: 38.4,
    vibrationMmS: 7.42,
    speedRpm: 3605,
    operatingHours: 18450,
    defects: [
      {
        id: 'defect-101',
        label: 'High-Cycle Fatigue Microcrack',
        severity: 'critical',
        confidence: 96.8,
        box: { x: 38, y: 32, width: 24, height: 35 },
        location: 'Rotor Blade #14 Leading Edge Mid-Chord',
        metric: 'Estimated Length: 0.88 mm (Growth Rate: +0.12 mm / 100 hrs)',
        recommendation: 'Immediate eddy-current NDT verification and borescope blade replacement. Do not exceed 3000 RPM.',
        standardsRef: 'ASME Section V Article 8 / GE GEK-10756',
        sopId: 'doc-sop-gt01-brg4',
      },
      {
        id: 'defect-102',
        label: 'Thermal Barrier Coating (TBC) Spalling',
        severity: 'warning',
        confidence: 91.2,
        box: { x: 64, y: 55, width: 18, height: 22 },
        location: 'Suction Face Stator Vane Ring',
        metric: 'Area: 4.2 cm² localized debonding',
        recommendation: 'Schedule recoating during upcoming Q4 scheduled outage.',
        standardsRef: 'ASTM C633 / ISO 14923',
        sopId: 'doc-sop-gt01-brg4',
      },
    ],
  },
  {
    id: 'sample-vision-2',
    title: 'TR-801 400kV Bushing Infrared Thermal Hotspot',
    machineId: 'TR-801',
    component: 'Phase B High-Voltage Bushing Terminal',
    timestamp: '2026-09-05T18:20:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    imageType: 'thermal',
    ambientTempC: 32.1,
    vibrationMmS: 0.85,
    speedRpm: 0,
    operatingHours: 42100,
    defects: [
      {
        id: 'defect-201',
        label: 'Terminal Clamp Resistance Hotspot',
        severity: 'critical',
        confidence: 98.4,
        box: { x: 42, y: 22, width: 20, height: 26 },
        location: 'Phase B Bushing Flange Bolted Connection',
        metric: 'Terminal Temp: 94.6°C (Delta-T over ambient: +62.5°C)',
        deltaT: '+62.5°C Delta-T',
        recommendation: 'Immediate electrical load de-rating to 60%. Schedule torque audit and contact grease application.',
        standardsRef: 'NETA MTS-2019 Table 100.18 / IEEE C57.19.00',
        sopId: 'doc-xfmr-dga',
      },
    ],
  },
  {
    id: 'sample-vision-3',
    title: 'P-402 Mechanical Seal Face Hydrocarbon Seepage',
    machineId: 'P-402',
    component: 'Drive-End Cartridge Mechanical Seal',
    timestamp: '2026-09-04T12:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    imageType: 'visible',
    ambientTempC: 28.5,
    vibrationMmS: 2.15,
    speedRpm: 2980,
    operatingHours: 8900,
    defects: [
      {
        id: 'defect-301',
        label: 'Plan 53A Barrier Fluid Micro-Seepage',
        severity: 'warning',
        confidence: 89.5,
        box: { x: 45, y: 48, width: 26, height: 28 },
        location: 'Gland Plate Throttle Bushing Drain Port',
        metric: 'Leak Rate: ~4 drops/min synthetic diester fluid',
        recommendation: 'Verify barrier reservoir level (RES-402). Inspect O-ring secondary elastomeric seal.',
        standardsRef: 'API Standard 682 4th Ed / ISO 21049',
        sopId: 'doc-pid-p402',
      },
    ],
  },
];

export const MOCK_AGENTS: IndustrialAgent[] = [
  {
    id: 'agent-sentinel',
    name: 'Telemetry Sentinel Agent',
    codeName: 'SENTINEL-SCADA-01',
    role: 'Continuous Modbus/OPC-UA Sensor Stream Monitor',
    description: 'High-frequency telemetry watchdog monitoring 420 industrial sensor channels at 50 Hz. Identifies statistical covariance anomalies and vibration zone breaches.',
    status: 'alert',
    vramMb: 3200,
    latencyMs: 14,
    opsCount: 184920,
    accuracyRate: 99.4,
    lastExecution: '1s ago',
    tags: ['Modbus TCP', 'OPC-UA', 'FFT Analytics', 'ISO-10816'],
  },
  {
    id: 'agent-reasoner',
    name: 'Diagnostic Reasoning Agent',
    codeName: 'REASONER-LLM-02',
    role: 'Root-Cause Synthesis & SOP Knowledge Retrieval',
    description: 'Air-gapped 7B parameter reasoning engine. Correlates physical telemetry signatures with indexed plant manuals, failure mode effect analysis (FMEA), and past work orders.',
    status: 'executing',
    vramMb: 8900,
    latencyMs: 82,
    opsCount: 14205,
    accuracyRate: 96.8,
    lastExecution: 'Just now',
    tags: ['Local vLLM', 'RAG Retrieval', 'FMEA Engine', 'Explainable AI'],
  },
  {
    id: 'agent-sil3',
    name: 'Safety Interlock Agent',
    codeName: 'INTERLOCK-SIL3-03',
    role: 'Safety Instrumented System (SIS) & LOTO Auditor',
    description: 'Deterministic safety boundary enforcer. Verifies that all copilot recommendations comply with IEC 61508/61511 safety integrity levels before display to human operators.',
    status: 'active',
    vramMb: 1100,
    latencyMs: 8,
    opsCount: 52100,
    accuracyRate: 100.0,
    lastExecution: '4s ago',
    tags: ['SIL-3 Certified', 'LOTO Logic', 'IEC 61511', 'Zero Override'],
  },
  {
    id: 'agent-vision',
    name: 'Edge Vision Defect Agent',
    codeName: 'VISION-YOLO-04',
    role: 'Optical & Thermal Anomaly Detection',
    description: 'On-premise vision transformer and YOLO model calibrated on 120k industrial defect images. Detects microcracks, thermal hotspots, cavitation pitting, and flange leaks.',
    status: 'active',
    vramMb: 5400,
    latencyMs: 24,
    opsCount: 3820,
    accuracyRate: 95.7,
    lastExecution: '12s ago',
    tags: ['Local TensorRT', 'FLIR Infrared', 'Microcrack Detect', 'ASME Stds'],
  },
];

export const MOCK_AGENT_TASKS: AgentTask[] = [
  {
    id: 'task-101',
    agentId: 'agent-sentinel',
    agentName: 'Telemetry Sentinel',
    title: 'Monitor GT-01 Bearing #4 Vibration Drift',
    priority: 'critical',
    status: 'running',
    progress: 84,
    startedAt: '2026-09-06T05:25:00Z',
    estimatedCompletion: 'Continuous',
    traceSteps: [
      'Polled Modbus channel AI-0442 @ 50 Hz',
      'Calculated 60s moving RMS variance',
      'Triggered threshold alert: 7.42 mm/s > 7.10 mm/s limit',
      'Dispatched telemetry packet to Diagnostic Reasoner',
    ],
  },
  {
    id: 'task-102',
    agentId: 'agent-reasoner',
    agentName: 'Diagnostic Reasoner',
    title: 'Synthesize SOP Remediation for ISO Zone D Breach',
    priority: 'high',
    status: 'running',
    progress: 92,
    startedAt: '2026-09-06T05:30:10Z',
    estimatedCompletion: 'In 2s',
    traceSteps: [
      'Ingested FFT spectrum features (1X 60.1Hz, sub-harmonic 25.8Hz)',
      'Retrieved SOP-MNT-GT01-BRG4 section 3.2',
      'Verified lube oil temperature correlation (+14.2°C)',
      'Generated load shedding step-by-step recommendation',
    ],
  },
  {
    id: 'task-103',
    agentId: 'agent-sil3',
    agentName: 'Safety Interlock Agent',
    title: 'Validate Automatic Derate Safety Envelope',
    priority: 'critical',
    status: 'completed',
    progress: 100,
    startedAt: '2026-09-06T05:30:45Z',
    estimatedCompletion: 'Completed',
    traceSteps: [
      'Checked SIL-3 bypass lock flags: NONE ACTIVE',
      'Validated minimum ramp rate: 10 MW/min meets thermal safety criteria',
      'Verified zero collision with grid dispatch minimum',
      'Appended cryptographic approval token #SIL-98214',
    ],
  },
];

export const MOCK_AGENT_LOGS: AgentLogEntry[] = [
  {
    id: 'log-1',
    timestamp: '05:31:22.140',
    agentCode: 'SENTINEL-SCADA-01',
    level: 'TELEMETRY',
    message: 'Sensor TAG-GT01-VIB-BRG4 sample 481020: 7.421 mm/s RMS (Phase: +44.2 deg). Signal SNR: 38 dB.',
  },
  {
    id: 'log-2',
    timestamp: '05:31:22.190',
    agentCode: 'SENTINEL-SCADA-01',
    level: 'WARN',
    message: 'Threshold breach: Vibration velocity exceeded ISO-10816 Zone C threshold (4.50 mm/s) by +64.9%.',
  },
  {
    id: 'log-3',
    timestamp: '05:31:22.250',
    agentCode: 'REASONER-LLM-02',
    level: 'INFO',
    message: 'Local vLLM context prompt built with 1,840 tokens. Initiating speculative decoding on GPU 0/1.',
  },
  {
    id: 'log-4',
    timestamp: '05:31:22.380',
    agentCode: 'INTERLOCK-SIL3-03',
    level: 'SECURITY',
    message: 'Zero-Egress Gateway verified: Packet egress filter 100% closed. Outbound socket attempts: 0.',
  },
  {
    id: 'log-5',
    timestamp: '05:31:22.420',
    agentCode: 'VISION-YOLO-04',
    level: 'INFO',
    message: 'TensorRT engine ready: Model YOLOv11x-Industrial loaded in VRAM (5,420 MB). Zero cloud dependency.',
  },
];

export const MOCK_AIRGAP_TELEMETRY: AirGapTelemetry = {
  airGapIsolated: true,
  physicalCableStatus: 'DISCONNECTED',
  egressPacketsBlocked: 48920,
  inboundPacketsBlocked: 12450,
  wanBytesSent: 0,
  localLoopbackBytes: 428901200,
  lanVlanId: 'VLAN-900-OT-ISOLATED',
  localRuntime: 'vLLM v0.6.2 (TensorRT-LLM Backend)',
  gpuDevice: 'Dual NVIDIA RTX A6000 Ada (48GB x 2 = 96GB VRAM)',
  vramAllocatedGb: 18.6,
  vramTotalGb: 96.0,
  modelChecksumVerified: true,
  modelSha256: '8b74c10a62df8942b012fa6b78912e8301928471928374659102938475610293',
  lastAuditTimestamp: '2026-09-06T05:31:00Z',
};

export const MOCK_CONFIDENCE_METRICS: ConfidenceMetrics = {
  overallScore: 95.4,
  retrievalConfidence: 96.2,
  telemetryAlignment: 98.1,
  visionDefectCertainty: 96.8,
  hallucinationRisk: 0.8,
  safetyMarginPassed: true,
  requiresDualSignoff: false,
  rationale: 'High convergence between live SCADA FFT telemetry, ISO-10816-3 standard tables, and verified plant emergency SOP chunk #12. Hallucination probability is negligible (<1%).',
};

export const MOCK_CERTIFICATIONS: SecurityCertification[] = [
  {
    standard: 'IEC 62443-4-2',
    title: 'Industrial Automation and Control Systems Cybersecurity',
    status: 'VERIFIED',
    clause: 'Level 4 Air-Gap Physical Isolation & Cryptographic Boundary',
    lastVerified: '2026-09-01',
  },
  {
    standard: 'ISO/IEC 27001:2022',
    title: 'Information Security Management - Annex A.13 Network Security',
    status: 'COMPLIANT',
    clause: 'Segregation in Networks & Zero Egress Transmission',
    lastVerified: '2026-08-15',
  },
  {
    standard: 'NERC CIP-005-7',
    title: 'Electronic Security Perimeter(s) for Bulk Electric Systems',
    status: 'AUDITED',
    clause: 'Dial-up and external routable protocol complete termination',
    lastVerified: '2026-08-28',
  },
  {
    standard: 'NIST SP 800-82 Rev 3',
    title: 'Guide to Industrial Control Systems (ICS) Security',
    status: 'VERIFIED',
    clause: 'Dual-Homed Air-Gap Bastion & Data Diode Simulation',
    lastVerified: '2026-09-04',
  },
];